apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.service: gleam-playground-db-claim
  name: gleam-playground-db-claim
  namespace: gleam-playground
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
