apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: redis
  name: redis
  namespace: gleam-playground
spec:
  ports:
  - name: '6379'
    port: 6379
    targetPort: 6379
  selector:
    io.service: redis
  type: ClusterIP
