apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: gleam-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.service: redis
    spec:
      containers:
      - args:
        - redis-server
        image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
      hostNetwork: false
