apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: gleam-playground-frontend
  name: gleam-playground-frontend
  namespace: gleam-playground
spec:
  ports:
  - name: '80'
    port: 80
    targetPort: 80
  selector:
    io.service: gleam-playground-frontend
  type: ClusterIP
