apiVersion: apps/v1
kind: Deployment
metadata:
  name: gleam-playground-frontend
  namespace: gleam-playground
spec:
  replicas: 2
  selector:
    matchLabels:
      io.service: gleam-playground-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.service: gleam-playground-frontend
    spec:
      containers:
      - image: nicklasxyz/gleam-playground-frontend:latest
        name: gleam-playground-frontend
      hostNetwork: false
