apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: gleam-playground-pgbouncer
  name: gleam-playground-pgbouncer
  namespace: gleam-playground
spec:
  ports:
  - name: '5432'
    port: 5432
    targetPort: 5432
  selector:
    io.service: gleam-playground-pgbouncer
  type: ClusterIP
